version: '3.1'

services:
  web:
    image: edisonarango/vpo:latest
    environment:
      SERVER: "True"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - db
    volumes:
      - cachepbf:/src/cache
    command: python app.py
    ports:
      - "80:80"

  db:
    image: mdillon/postgis:latest
    container_name: vpo_postgis
    environment:
      POSTGRES_DB: geo24
      POSTGRES_USER: geo
      POSTGRES_PASSWORD: geo
    volumes:
      - postgisdata:/var/lib/postgresql/data
      - ./shapefiles:/shapefiles
    ports:
      - "5432"

  pg_admin:
    image: chorss/docker-pgadmin4
    container_name: vpo_pgadmin
    ports:
      - "5050:5050"

volumes:
  postgisdata:
  cachepbf: